language: java
addons:
  apt:
    packages:
    - atlassian-plugin-sdk
install:
  - bundle install --path vendor/bundle
script:
  - rake --trace
after_script:
  - rake after_build --trace
deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: output/*.nupkg
    api_key:
      secure: WmW8P+7vxPmVUnIbhVkfY4TzjN8bC8uguHc10fQedmSWCzJ7Lq0c6kXKoKAWKPUTmDn9+IyAYyCGXs8rjIs7ZPavd8p3vMDTFl9K72bZhCpnKMLhK2/1zWBijfAbVehK2cTGiSLUSROnvNcpX7zRj7QQWhm+iBg8YJt87gBSkg68vZN9YL+N2nUdHN2txrFKeGiH+nSce2v4jyZD+JKC74oO1rkgLx1gsJ2YEc5ZmqAibI9dsWK+Yr1SqQu/xPnanM3QCno0GKdWvL4IJijllxWTIQ8HvvZjoqXOKPkObaI2evzbvp5kT5q8rAZJ1sqX4m7hyXQcEIb1xcJijv5Topq0hr3dsPgIYMTq40DJuF7qsoAn7/GkTQrPWyv4lnXN2Sfy886iMhkUw70JHArNf4Hs3YbvnYBcntqk5yJ+rlnKRJjUKYsCxQ6/Yc4QM0H8wCgdDRS3fRYHa640DrlDm8SzceViyJzGTbhdskKvUgSbvAJU+YN6VnCvjXwyj0SD1cAIFiO18FZMEHegJ2CSaF8TkEA/6WgVtge5OxHgDBQqDmgAynfWrXyKFRNbJ2K0gjgdybtCxGwo7YpX183HWYxSb2s89bMl9wuXnxIAZ+nocDxpr3AZO8fXFET5Pr7c+2zx7VjeX66t0Wqe3pYM4yCO/FdhToHxJK4k2Of4Jds=
    on:
      tags: false
      all_branches: true
branches:
  only:
  - /^release.*/
env:
  global:
  #GIT_TAG_PUSHER
  - secure: YcGPIUFRX8N1xp835zo2RWMmBQXxrVrsqx7vFK8iAhdYYKO0tc2sAYjjxrDuWy7gAbhyW1dnm3I6wQKluNIhmHCFY486BlGR6hwVgNy7eRtmMqGJ2E8be1+sxe2di09H6h/s1+PNqx+snWU/WK5tFVx9PCZmDfeYNJlWgoCU4jAEV+7Wo240aUtbxv6++QSzr3mUMCh3YSTtUqMzScmP7GBTQZVejF2+tB2taGH2rcmc5SCovT3t5eZqoeosgNNHVYQYRsS92ScANX00KxxVzMl61uHKOUS4hvNTB2e9FfFVIjIfZIImjNJ6BMHFVfP6l2TRu3ajlZpTHX/Y8sdUnfgzrc6qniFDAkUNxgKaj3+LUKMABIjxfMxbk7Mp/qyGftj7iGG+7WJuHntu3KJn8afQgwcOvc8Go2pr/xVYNPQskgooUtup9kFkZpiT5xwe4AzyKcUwkwzntlNGLvSlGZuQLeDljtuxEECobblZfAVv5mPWjZYKFYuueouXG9YjqtgV2Tmsdx1FIWRs/ADvowL1OiiszRakoRo/bdN/N8vmSFYUDCrSQl/RwoFZ/jklwZ3ayMQSI4E5YGpSDYdjJPvJCPzv38OtuWN8C+FLHwG73zlXf+fMNnqOCN6UT5CPj2RUWpzPBjmqTugU+/3V8HxyclDuSWy36jFAwDzgxGE=
